//created on: Sep 8, 2016
package org.rustom.shroff.calculatorFromScracth

//list any import classes here.
import org.rustom.shroff.calculatorFromScracth.Calculation


//declare any global variables here

rule "Subtraction Rule"
    //include attributes such as "salience" here...
    no-loop // Not applicable here but can be very usfull to remove infinite loops.
    salience myA // higher priority then the above rule. Hence it will execute before Addition Rule.
    enabled (myA != myB)
    when
       myCalculation : Calculation( operation.equals("subtraction"), myA : a, myB: b, myResult: result )
    then
    
        
    	myResult = myA-myB;
        System.out.println( "subtraction of "+ myCalculation.getA() +" and "+ myCalculation.getB() +" is "+ myResult);
		//use update or modify statement here for chaing to another rule
		modify(myCalculation){
			setOperation("addition")   //This statement translates to myCalculation.setOperation
		}
		
		// you can also use "insert(new SomeClass()) based on the outcome of when"
end
