//created on: Sep 8, 2016
package org.rustom.shroff.calculatorFromScracth

//list any import classes here.
import org.rustom.shroff.calculatorFromScracth.Calculation


//declare any global variables here

rule "Subtraction Rule"
    //include attributes such as "salience" here...
    no-loop // Not applicable here but can be very usfull to remove infinite loops.
    salience myA // higher priority then the above rule. Hence it will execute before Addition Rule.
    enabled (myA != myB)
    when
    	myPerson : Person(name.equals("riaz"), calculation.operation.equals("subtraction"), myA : calculation.a, myB: calculation.b, myResult: calculation.result)
    	
    then
    
        
    	myPerson.getCalculation().setResult(myA-myB);
    	//requiredCalculation.setResult(myA+myB);
    	//myResult = myA+myB;
    	//result = myResult;
        System.out.println( "subtraction of "+ myA +" and "+ myB +" is "+ myPerson.getCalculation().getResult());
		//modify(myCalculation){
			//setOperation("addition")   //This statement translates to myCalculation.setOperation
		//}
end
