//created on: Sep 8, 2016
package org.rustom.shroff.calculatorFromScracth

//list any import classes here.
import org.rustom.shroff.calculatorFromScracth.Calculation


//declare any global variables here




rule "Addition Rule"
	salience 1
	agenda-group "addition"  //agenda will take precedence over salience
	//ruleflow-group     // only one rule from this group gets fired
	//@propertyReactive  // tells the rules engine to monitor the property of a class 
	//@watch(property1, property2, ...)
    when
        myCalculation: Calculation( operation.equals("addition"), myA : a, myB: b, myResult: result )
    then
    	myCalculation.setResult(myA+myB);
    	//result = myResult;
        System.out.println( "addition of "+ myA +" and "+ myB +" is "+ myCalculation.getResult());
        kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("MAIN").setFocus();
       	 
       //main is the default agenda group for all the rools present in a kbase
        

end


